In [27]:
%load_ext autoreload
%autoreload 2
import tensorflow as tf
from networks import Encoder, Decoder, MetaModel, TrainingCallback
import numpy as np
import ast
from sindy import SINDy
import os


x, x_dot = np.load("datalorenz/paper500.npy").astype(np.float32)
x = tf.reshape(x,[-1,128])[:1000]
x_dot = tf.reshape(x,[-1,128])[:1000]
    

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [28]:

encoder = Encoder()
decoder = Decoder()
sindy = SINDy()
models = [encoder, decoder, sindy]
    
metamodel = MetaModel(models, total_epochs=400, when_zero_lambda3=1000)
metamodel.compile_models()


In [29]:
history = metamodel.fit(x=x, y=x_dot, epochs=50, batch_size=25,
                callbacks=[TrainingCallback(), tf.keras.callbacks.TensorBoard("logs/prueba3"),
                              ])

Epoch 1/50
40/40 [==============================] - 0s 11ms/step - Total Loss: 0.0737 - Loss_0: 0.0737 - Loss_1: 1.8537e-05 - Loss_2: 0.0000e+00 - Loss_3: 9.0903e-06
Epoch 2/50
40/40 [==============================] - 0s 3ms/step - Total Loss: 0.0836 - Loss_0: 0.0836 - Loss_1: 1.7871e-05 - Loss_2: 0.0000e+00 - Loss_3: 8.7463e-06
Epoch 3/50
40/40 [==============================] - 0s 3ms/step - Total Loss: 0.0291 - Loss_0: 0.0291 - Loss_1: 1.5070e-05 - Loss_2: 0.0000e+00 - Loss_3: 8.3953e-06
Epoch 4/50
40/40 [==============================] - 0s 3ms/step - Total Loss: 0.1081 - Loss_0: 0.1081 - Loss_1: 2.0727e-05 - Loss_2: 0.0000e+00 - Loss_3: 8.0490e-06
Epoch 5/50
40/40 [==============================] - 0s 3ms/step - Total Loss: 0.0887 - Loss_0: 0.0887 - Loss_1: 2.2314e-05 - Loss_2: 0.0000e+00 - Loss_3: 7.7059e-06
Epoch 6/50
40/40 [==============================] - 0s 3ms/step - Total Loss: 0.0154 - Loss_0: 0.0154 - Loss_1: 1.4730e-05 - Loss_2: 0.0000e+00 - Loss_3: 7.3935e-06
Epoch 7/5

40/40 [==============================] - 0s 3ms/step - Total Loss: 0.0172 - Loss_0: 0.0171 - Loss_1: 2.3177e-05 - Loss_2: 0.0000e+00 - Loss_3: 7.2119e-06
Epoch 21/50
40/40 [==============================] - 0s 3ms/step - Total Loss: 0.0121 - Loss_0: 0.0121 - Loss_1: 1.7001e-05 - Loss_2: 0.0000e+00 - Loss_3: 7.2151e-06
Epoch 22/50
40/40 [==============================] - 0s 3ms/step - Total Loss: 0.0113 - Loss_0: 0.0113 - Loss_1: 1.9393e-05 - Loss_2: 0.0000e+00 - Loss_3: 7.2188e-06
Epoch 23/50
40/40 [==============================] - 0s 3ms/step - Total Loss: 0.0227 - Loss_0: 0.0227 - Loss_1: 2.2394e-05 - Loss_2: 0.0000e+00 - Loss_3: 7.2196e-06
Epoch 24/50
40/40 [==============================] - 0s 3ms/step - Total Loss: 0.0237 - Loss_0: 0.0236 - Loss_1: 1.8437e-05 - Loss_2: 0.0000e+00 - Loss_3: 7.2247e-06
Epoch 25/50
40/40 [==============================] - 0s 3ms/step - Total Loss: 0.0074 - Loss_0: 0.0074 - Loss_1: 1.3907e-05 - Loss_2: 0.0000e+00 - Loss_3: 7.2229e-06
Epoch 26/50
40/4

Epoch 41/50
40/40 [==============================] - 0s 3ms/step - Total Loss: 0.0100 - Loss_0: 0.0100 - Loss_1: 1.4123e-05 - Loss_2: 0.0000e+00 - Loss_3: 7.1765e-06
Epoch 42/50
40/40 [==============================] - 0s 6ms/step - Total Loss: 0.0110 - Loss_0: 0.0109 - Loss_1: 1.8037e-05 - Loss_2: 0.0000e+00 - Loss_3: 7.1648e-06
Epoch 43/50
40/40 [==============================] - 0s 2ms/step - Total Loss: 0.0122 - Loss_0: 0.0122 - Loss_1: 1.6224e-05 - Loss_2: 0.0000e+00 - Loss_3: 7.1593e-06
Epoch 44/50
40/40 [==============================] - 0s 2ms/step - Total Loss: 0.0296 - Loss_0: 0.0296 - Loss_1: 2.2966e-05 - Loss_2: 0.0000e+00 - Loss_3: 7.1490e-06
Epoch 45/50
40/40 [==============================] - 0s 3ms/step - Total Loss: 0.0232 - Loss_0: 0.0232 - Loss_1: 2.7612e-05 - Loss_2: 0.0000e+00 - Loss_3: 7.1409e-06
Epoch 46/50
40/40 [==============================] - 0s 3ms/step - Total Loss: 0.0243 - Loss_0: 0.0243 - Loss_1: 1.9006e-05 - Loss_2: 0.0000e+00 - Loss_3: 7.1357e-06
Epoc

In [36]:
sindy.load_weights("nets/sindy_0/")

In [37]:
sindy.weights

[<tf.Tensor: shape=(3, 27), dtype=float32, numpy=
 array([[-0.9311571 ,  1.3730997 , -0.18049856, -0.23604348, -0.8861915 ,
          0.34579983,  0.        ,  0.3817444 ,  0.6329095 , -0.46864775,
          0.20121433,  0.        ,  0.        ,  1.4880794 ,  0.8682103 ,
         -0.7623767 ,  0.76911217,  0.        , -2.235712  ,  1.3080964 ,
          1.2098081 , -1.1070364 , -1.3574041 , -1.7704686 , -0.71796733,
         -0.5128483 ,  1.8050104 ],
        [-0.65252423,  0.17881115,  1.0176535 , -0.22862421,  1.2786188 ,
         -0.45869717, -0.42945144, -0.2683546 ,  1.3455132 , -0.28287098,
         -0.6332829 ,  0.5585188 , -0.8899651 ,  2.2761014 , -0.33276758,
         -1.0422409 , -0.13713206, -1.0998034 ,  0.        , -0.87539   ,
          0.5636082 ,  1.5775213 , -1.6637301 ,  0.59779716, -0.6056043 ,
          1.464332  ,  0.92218494],
        [-1.5582777 ,  1.0950025 ,  2.142236  , -0.66036254,  0.66531783,
          0.5450642 ,  0.39311463, -2.4012308 ,  1.6103411 ,  1.

In [63]:
sindy = SINDy()
sindy.load_weights("nets/sindy_11/")

ValueError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on nets/sindy_11/: Not found: nets/sindy_11; No such file or directory

In [18]:
from sindy import SINDy
sindy1 = SINDy()

In [20]:
sindy1.name

'sin_dy_1'

In [9]:
coeffs = tf.Variable(np.ones((3,27)).astype(np.float32), trainable=True, name="sindy/dense/kernel:0")
coeffs

<tf.Variable 'Variable:0' shape=(3, 27) dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [58]:
sindy.weigths

[<tf.Variable 'Variable:0' shape=(3, 27) dtype=float32, numpy=
 array([[-2.48601614e-03,  8.35985005e-01, -1.08248937e+00,
         -1.25054210e-01,  2.19034106e-01, -1.66024411e+00,
         -1.19687581e+00, -4.92233634e-02,  8.97786766e-02,
          3.82149875e-01,  9.09135304e-03,  2.49032676e-01,
          7.79314060e-03,  5.54208532e-02, -8.83790329e-02,
         -3.96450646e-02,  1.44127405e+00, -2.65611023e-01,
          1.15535867e+00, -1.99022663e+00,  2.95111537e-01,
          4.73870263e-02, -8.94377083e-02, -3.42485398e-01,
          7.68711209e-01, -7.77051866e-01, -3.71877491e-01],
        [ 6.50211632e-01, -8.26581493e-02,  1.02030349e+00,
          7.19511807e-02, -5.15373468e-01,  3.45013499e-01,
         -1.21267819e+00,  1.25622785e+00, -1.47071671e+00,
         -9.12182629e-02,  5.38204551e-01,  7.74763823e-02,
          1.82412457e+00,  1.05103528e+00,  1.50815874e-01,
         -2.12940145e+00,  5.59756756e-01,  1.24723963e-01,
          3.04355519e-04,  1.0376338