In [8]:
%load_ext autoreload
%autoreload 2
import tensorflow as tf
from networks import Encoder, Decoder, MetaModel, TrainingCallback
import numpy as np
import ast
from sindy import SINDy
import os


x, x_dot = np.load("datalorenz/paper500.npy").astype(np.float32)
x = tf.reshape(x,[-1,128])[:1000]
x_dot = tf.reshape(x,[-1,128])[:1000]
    

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [9]:

encoder = Encoder()
decoder = Decoder()
sindy = SINDy()
models = [encoder, decoder, sindy]
    
metamodel = MetaModel(models, total_epochs=400, when_zero_lambda3=1000)
metamodel.compile_models()


In [10]:
history = metamodel.fit(x=x, y=x_dot, epochs=50, batch_size=25,
                callbacks=[TrainingCallback(), tf.keras.callbacks.TensorBoard("logs/prueba3"),
                              ])

Epoch 1/50


AttributeError: in user code:

    /home/cooper-cooper/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py:806 train_function  *
        return step_function(self, iterator)
    /home/cooper-cooper/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py:796 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    /home/cooper-cooper/.local/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_lib.py:1211 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /home/cooper-cooper/.local/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_lib.py:2585 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /home/cooper-cooper/.local/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_lib.py:2945 _call_for_each_replica
        return fn(*args, **kwargs)
    /home/cooper-cooper/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py:789 run_step  **
        outputs = model.train_step(data)
    /home/cooper-cooper/Desktop/sandra/networks.py:99 train_step
        model.optimizer.apply_gradients(zip(gradient, model.trainable_variables))
    /home/cooper-cooper/.local/lib/python3.6/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:519 apply_gradients
        self._create_all_weights(var_list)
    /home/cooper-cooper/.local/lib/python3.6/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:704 _create_all_weights
        self._create_slots(var_list)
    /home/cooper-cooper/.local/lib/python3.6/site-packages/tensorflow/python/keras/optimizer_v2/adam.py:127 _create_slots
        self.add_slot(var, 'm')
    /home/cooper-cooper/.local/lib/python3.6/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:739 add_slot
        var_key = _var_key(var)
    /home/cooper-cooper/.local/lib/python3.6/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:1297 _var_key
        if var._in_graph_mode:

    AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute '_in_graph_mode'


In [7]:
encoder.weights

[<tf.Variable 'encoder_1/dense_6/kernel:0' shape=(128, 64) dtype=float32, numpy=
 array([[-8.30169022e-03, -6.48574624e-03, -1.78725012e-02, ...,
         -1.18210847e-02, -5.10080531e-03,  1.13554597e-02],
        [ 1.74841583e-02, -1.81726087e-02,  2.18860805e-06, ...,
          1.17260665e-02,  1.41436309e-02, -8.38480610e-03],
        [ 1.51841752e-02, -1.39221791e-02, -9.66732297e-03, ...,
          1.49070621e-02, -1.43548194e-02,  1.09513868e-02],
        ...,
        [-1.78354103e-02, -7.21635297e-03, -1.83079280e-02, ...,
          1.34291053e-02,  4.11658920e-03,  1.22468099e-02],
        [ 1.85891725e-02,  7.42485188e-03,  2.06268765e-03, ...,
          1.19218994e-02,  6.11864403e-03,  1.58413388e-02],
        [-1.63776614e-03, -4.33084276e-03,  4.79440019e-03, ...,
         -1.13189574e-02,  5.24195656e-03, -1.51079120e-02]], dtype=float32)>,
 <tf.Variable 'encoder_1/dense_6/bias:0' shape=(64,) dtype=float32, numpy=
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0

In [63]:
sindy = SINDy()
sindy.load_weights("nets/sindy_11/")

ValueError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on nets/sindy_11/: Not found: nets/sindy_11; No such file or directory

In [54]:
sindy.weigths

[<tf.Variable 'Variable:0' shape=(3, 27) dtype=float32, numpy=
 array([[-2.48601614e-03,  8.35985005e-01, -1.08248937e+00,
         -1.25054210e-01,  2.19034106e-01, -1.66024411e+00,
         -1.19687581e+00, -4.92233634e-02,  8.97786766e-02,
          3.82149875e-01,  9.09135304e-03,  2.49032676e-01,
          7.79314060e-03,  5.54208532e-02, -8.83790329e-02,
         -3.96450646e-02,  1.44127405e+00, -2.65611023e-01,
          1.15535867e+00, -1.99022663e+00,  2.95111537e-01,
          4.73870263e-02, -8.94377083e-02, -3.42485398e-01,
          7.68711209e-01, -7.77051866e-01, -3.71877491e-01],
        [ 6.50211632e-01, -8.26581493e-02,  1.02030349e+00,
          7.19511807e-02, -5.15373468e-01,  3.45013499e-01,
         -1.21267819e+00,  1.25622785e+00, -1.47071671e+00,
         -9.12182629e-02,  5.38204551e-01,  7.74763823e-02,
          1.82412457e+00,  1.05103528e+00,  1.50815874e-01,
         -2.12940145e+00,  5.59756756e-01,  1.24723963e-01,
          3.04355519e-04,  1.0376338

In [58]:
sindy.weigths

[<tf.Variable 'Variable:0' shape=(3, 27) dtype=float32, numpy=
 array([[-2.48601614e-03,  8.35985005e-01, -1.08248937e+00,
         -1.25054210e-01,  2.19034106e-01, -1.66024411e+00,
         -1.19687581e+00, -4.92233634e-02,  8.97786766e-02,
          3.82149875e-01,  9.09135304e-03,  2.49032676e-01,
          7.79314060e-03,  5.54208532e-02, -8.83790329e-02,
         -3.96450646e-02,  1.44127405e+00, -2.65611023e-01,
          1.15535867e+00, -1.99022663e+00,  2.95111537e-01,
          4.73870263e-02, -8.94377083e-02, -3.42485398e-01,
          7.68711209e-01, -7.77051866e-01, -3.71877491e-01],
        [ 6.50211632e-01, -8.26581493e-02,  1.02030349e+00,
          7.19511807e-02, -5.15373468e-01,  3.45013499e-01,
         -1.21267819e+00,  1.25622785e+00, -1.47071671e+00,
         -9.12182629e-02,  5.38204551e-01,  7.74763823e-02,
          1.82412457e+00,  1.05103528e+00,  1.50815874e-01,
         -2.12940145e+00,  5.59756756e-01,  1.24723963e-01,
          3.04355519e-04,  1.0376338